version: '3'
volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    environment:
      POSTGRES_USER: go-gin
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: demo
      PGDATA: '/data/postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'