version: '3'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ['postgres', '-cshared_preload_libraries=pg_stat_statements']
    environment:
      POSTGRES_USER: go-gin
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: demo
      PGDATA: '/data/postgres'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
